# Generated by Django 3.2.3 on 2021-05-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categorie',
            field=models.CharField(choices=[('Actualités', 'Actualités'), ('Prgrammation', 'Programmation')], default='Actualités', max_length=250),
        ),
    ]
